# Generated by Django 5.2.8 on 2025-12-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PM', 'Менеджер проекта'), ('DEV', 'Разработчик')], default='ADMIN', max_length=10, verbose_name='Роль пользователя'),
        ),
    ]
