# Generated by Django 5.2.8 on 2025-11-29 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('cooperation_format', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('OUTSOURCE', 'Outsource'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=50)),
                ('contacts', models.TextField(help_text='Телефоны, email')),
                ('passport_data', models.TextField(blank=True, help_text='Паспортные данные (будут зашифрованы)', null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('workload', models.CharField(max_length=255)),
                ('competencies', models.TextField()),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('deadline', models.DateField(db_index=True)),
                ('completion_percent', models.PositiveIntegerField(default=0, help_text='Процент завершения (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('documents', models.FileField(blank=True, null=True, upload_to='project_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'xls', 'xlsx'])])),
                ('stages', models.JSONField(blank=True, default=list, help_text="Все этапы проекта в формате [{name: 'Этап 1', status: 'in_progress', deadline: '2024-01-01'}]")),
                ('active_stage', models.CharField(blank=True, help_text='Текущий этап', max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
