# Generated by Django 5.2.8 on 2025-12-12 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, default='', max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, default='', max_length=255, verbose_name='Должность')),
                ('cooperation_format', models.CharField(blank=True, choices=[('FULL_TIME', 'Полная занятость'), ('PART_TIME', 'Частичная занятость'), ('OUTSOURCE', 'Аутсорс'), ('CONTRACT', 'Контракт')], default='FULL_TIME', max_length=50, verbose_name='Формат сотрудничества')),
                ('contacts', models.TextField(blank=True, default='', verbose_name='Контакты')),
                ('passport_data', models.TextField(blank=True, null=True, verbose_name='Паспортные данные')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарплата')),
                ('workload', models.CharField(blank=True, default='', max_length=255, verbose_name='Занятость')),
                ('competencies', models.TextField(blank=True, default='', verbose_name='Компетенции')),
                ('strengths', models.TextField(blank=True, default='', verbose_name='Сильные стороны')),
                ('weaknesses', models.TextField(blank=True, default='', verbose_name='Слабые стороны')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Комментарии')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Разработчик',
                'verbose_name_plural': 'Разработчики',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=255, verbose_name='Название проекта')),
                ('customer_name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Заказчик')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая сумма')),
                ('deadline', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дедлайн')),
                ('completion_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Готовность (%)')),
                ('stages', models.TextField(blank=True, default='', help_text='Введите этапы проекта по порядку', verbose_name='Этапы проекта')),
                ('active_stage', models.CharField(blank=True, default='', max_length=255, verbose_name='Текущий этап')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('developers', models.ManyToManyField(blank=True, related_name='projects', to='crm.developer', verbose_name='Разработчики')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Допустимые форматы: pdf, doc, docx, txt, xls, xlsx, zip, rar', upload_to='project_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'xls', 'xlsx', 'zip', 'rar'])], verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Документ проекта',
                'verbose_name_plural': 'Документы проекта',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
