# Generated by Django 5.2.8 on 2026-01-06 04:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код колонки')),
                ('title', models.CharField(max_length=100, verbose_name='Название колонки')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, default='', max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, default='', max_length=255, verbose_name='Должность')),
                ('cooperation_format', models.CharField(blank=True, choices=[('FULL_TIME', 'Полная занятость'), ('PART_TIME', 'Частичная занятость'), ('OUTSOURCE', 'Аутсорс'), ('CONTRACT', 'Контракт')], default='FULL_TIME', max_length=50, verbose_name='Формат сотрудничества')),
                ('contacts', models.TextField(blank=True, default='', verbose_name='Контакты')),
                ('passport_data', models.TextField(blank=True, null=True, verbose_name='Паспортные данные')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарплата')),
                ('workload', models.CharField(blank=True, default='', max_length=255, verbose_name='Занятость')),
                ('competencies', models.TextField(blank=True, default='', verbose_name='Компетенции')),
                ('strengths', models.TextField(blank=True, default='', verbose_name='Сильные стороны')),
                ('weaknesses', models.TextField(blank=True, default='', verbose_name='Слабые стороны')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Комментарии')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Разработчик',
                'verbose_name_plural': 'Разработчики',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=255, verbose_name='Название проекта')),
                ('customer_name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Заказчик')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая сумма')),
                ('deadline', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дедлайн')),
                ('completion_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Готовность (%)')),
                ('stages', models.TextField(blank=True, default='', help_text='Введите этапы проекта по порядку', verbose_name='Этапы проекта')),
                ('active_stage', models.TextField(blank=True, default='', verbose_name='Текущий этап')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('kanban_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен канбана')),
                ('files_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('developers', models.ManyToManyField(blank=True, related_name='projects', to='crm.developer', verbose_name='Разработчики')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KanbanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('assignee_kind', models.CharField(choices=[('none', '—'), ('developer', 'Разработчик'), ('user', 'Пользователь'), ('customer', 'Заказчик')], default='none', max_length=16, verbose_name='Тип исполнителя')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн задачи')),
                ('assignee_developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.developer', verbose_name='Исполнитель (разработчик)')),
                ('assignee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель (пользователь)')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.kanbancolumn', verbose_name='Колонка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_tasks', to='crm.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача канбана',
                'verbose_name_plural': 'Задачи канбана',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='kanbancolumn',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_columns', to='crm.project'),
        ),
        migrations.CreateModel(
            name='ProjectFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.projectfolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='crm.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to='project_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.projectfolder')),
            ],
        ),
        migrations.CreateModel(
            name='KanbanTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('move', 'Move'), ('reorder', 'Reorder'), ('delete', 'Delete')], max_length=20)),
                ('from_column', models.CharField(blank=True, max_length=50, null=True)),
                ('to_column', models.CharField(blank=True, max_length=50, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='crm.kanbantask', verbose_name='Задача канбана')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_actions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_activity', to='crm.project')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['project', '-created_at'], name='crm_kanbant_project_0d4f38_idx'), models.Index(fields=['task', '-created_at'], name='crm_kanbant_task_id_0ab631_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='kanbancolumn',
            unique_together={('project', 'code')},
        ),
    ]
