# Generated by Django 5.2.8 on 2025-11-29 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='projects', to='crm.developer'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsible',
            field=models.ForeignKey(help_text='PM или Admin, ответственный за проект', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
