# Generated by Django 5.2.8 on 2025-12-03 09:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['full_name'], 'verbose_name': 'Разработчик', 'verbose_name_plural': 'Разработчики'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='developer',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='competencies',
            field=models.TextField(blank=True, default='', help_text='Технологии, языки программирования, фреймворки', verbose_name='Компетенции'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='contacts',
            field=models.TextField(blank=True, default='', help_text='Телефоны, email и другие контакты', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='cooperation_format',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Полная занятость'), ('PART_TIME', 'Частичная занятость'), ('OUTSOURCE', 'Аутсорс'), ('CONTRACT', 'Контракт')], default='FULL_TIME', max_length=50, verbose_name='Формат сотрудничества'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='passport_data',
            field=models.TextField(blank=True, help_text='Паспортные данные (конфиденциально)', null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Зарплата в рублях', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='strengths',
            field=models.TextField(blank=True, default='', verbose_name='Сильные стороны'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='weaknesses',
            field=models.TextField(blank=True, default='', verbose_name='Слабые стороны'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='workload',
            field=models.CharField(blank=True, default='', help_text='Например: 80%, занят до конца месяца', max_length=255, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='project',
            name='active_stage',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Текущий этап'),
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_percent',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Процент выполнения', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Готовность (%)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Наименование заказчика'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Общий дедлайн'),
        ),
        migrations.AlterField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='projects', to='crm.developer', verbose_name='Разработчики'),
        ),
        migrations.AlterField(
            model_name='project',
            name='documents',
            field=models.FileField(blank=True, help_text='Договоры, NDA, Акты и др.', null=True, upload_to='project_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'xls', 'xlsx', 'zip', 'rar'])], verbose_name='Документы проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Ответственный менеджер проекта или администратор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stages',
            field=models.JSONField(blank=True, default=list, help_text='Этапы проекта в формате JSON', verbose_name='Этапы проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Общая стоимость в рублях', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
