# Generated by Django 5.2.8 on 2025-12-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_developer_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='full_name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='ФИО'),
        ),
    ]
