# Generated by Django 5.2.8 on 2025-12-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_developer_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Название проекта'),
        ),
    ]
