# Generated by Django 5.2.8 on 2025-12-10 11:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_project_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='documents',
        ),
        migrations.AlterField(
            model_name='developer',
            name='competencies',
            field=models.TextField(blank=True, default='', verbose_name='Компетенции'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='contacts',
            field=models.TextField(blank=True, default='', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='passport_data',
            field=models.TextField(blank=True, null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='workload',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Готовность (%)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stages',
            field=models.JSONField(blank=True, default=list, verbose_name='Этапы проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая сумма'),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'xls', 'xlsx', 'zip', 'rar'])], verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Документ проекта',
                'verbose_name_plural': 'Документы проекта',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
